//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication.BooksServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string authorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string genreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string yearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string authorName {
            get {
                return this.authorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.authorNameField, value) != true)) {
                    this.authorNameField = value;
                    this.RaisePropertyChanged("authorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string genre {
            get {
                return this.genreField;
            }
            set {
                if ((object.ReferenceEquals(this.genreField, value) != true)) {
                    this.genreField = value;
                    this.RaisePropertyChanged("genre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string year {
            get {
                return this.yearField;
            }
            set {
                if ((object.ReferenceEquals(this.yearField, value) != true)) {
                    this.yearField = value;
                    this.RaisePropertyChanged("year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BooksServiceReference.IBookService")]
    public interface IBookService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/getBooksList", ReplyAction="http://tempuri.org/IBookService/getBooksListResponse")]
        ConsoleApplication.BooksServiceReference.Book[] getBooksList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/getBooksList", ReplyAction="http://tempuri.org/IBookService/getBooksListResponse")]
        System.Threading.Tasks.Task<ConsoleApplication.BooksServiceReference.Book[]> getBooksListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/addBook", ReplyAction="http://tempuri.org/IBookService/addBookResponse")]
        void addBook(ConsoleApplication.BooksServiceReference.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/addBook", ReplyAction="http://tempuri.org/IBookService/addBookResponse")]
        System.Threading.Tasks.Task addBookAsync(ConsoleApplication.BooksServiceReference.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/Edit", ReplyAction="http://tempuri.org/IBookService/EditResponse")]
        void Edit(ConsoleApplication.BooksServiceReference.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/Edit", ReplyAction="http://tempuri.org/IBookService/EditResponse")]
        System.Threading.Tasks.Task EditAsync(ConsoleApplication.BooksServiceReference.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/deleteBook", ReplyAction="http://tempuri.org/IBookService/deleteBookResponse")]
        void deleteBook(int bookID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/deleteBook", ReplyAction="http://tempuri.org/IBookService/deleteBookResponse")]
        System.Threading.Tasks.Task deleteBookAsync(int bookID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookServiceChannel : ConsoleApplication.BooksServiceReference.IBookService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookServiceClient : System.ServiceModel.ClientBase<ConsoleApplication.BooksServiceReference.IBookService>, ConsoleApplication.BooksServiceReference.IBookService {
        
        public BookServiceClient() {
        }
        
        public BookServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsoleApplication.BooksServiceReference.Book[] getBooksList() {
            return base.Channel.getBooksList();
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication.BooksServiceReference.Book[]> getBooksListAsync() {
            return base.Channel.getBooksListAsync();
        }
        
        public void addBook(ConsoleApplication.BooksServiceReference.Book book) {
            base.Channel.addBook(book);
        }
        
        public System.Threading.Tasks.Task addBookAsync(ConsoleApplication.BooksServiceReference.Book book) {
            return base.Channel.addBookAsync(book);
        }
        
        public void Edit(ConsoleApplication.BooksServiceReference.Book book) {
            base.Channel.Edit(book);
        }
        
        public System.Threading.Tasks.Task EditAsync(ConsoleApplication.BooksServiceReference.Book book) {
            return base.Channel.EditAsync(book);
        }
        
        public void deleteBook(int bookID) {
            base.Channel.deleteBook(bookID);
        }
        
        public System.Threading.Tasks.Task deleteBookAsync(int bookID) {
            return base.Channel.deleteBookAsync(bookID);
        }
    }
}
